name: Generate CSS from Design Tokens

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Style Dictionary
      run: npm run build
 
    - name: Commit Generated Platform Deliverables
      id: "auto-commit-action"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update design tokens
        
    - name: Bump version
      run: npm version patch

    - name: Commit Generated Platform Deliverables
      id: "auto-commit-action-2"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: bump version
