# name: Bump Version

# on:
#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+'

# jobs:
#   bump_version:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Bump Version
#         run: npm version patch -m "Bump version to %s"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Commit update package.json and package-lock.json
#         id: "auto-commit-action"
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: commit bumped package.json
        